module.exports ={
    url: 'http://localhost:3000/#/',
    elements:{

        getStartedBtn: ('button[name="nextButton"]'),
        selectLoan: ('#loanTypes'),
        propertyType:('#propertyTypes'),
        typeNextBtn: ('button[name="nextButton"]'),
        cityName: ('input[name="city"]'),
        cityNextBtn: ('button[name="nextButton"]'),
        primaryBtn: ('button[value="Primary Home"]'),
        rentalBtn: ('button[value="Rental Property"]'),
        secondaryBtn: ('button[value="Secondary Home"]'),
        yesBtn: ('button[name="yesButton"]'),
        noBtn: ('button[name="noButton"]'),
        price:('input[name="price"]'),
        downPay:('input[name="down"]'),
        moneyBtn: ('.wSix-btn'),
        exCreditBtn: ('button[value="excellent"]'),
        gdCreditBtn: ('button[value="good"]'),
        frCreditBtn: ('button[value="fair"]'),
        prCreditBtn: ('button[value="poor"]'),
        noBankForeBtn: ('button[value="Has never been in bankruptcy"]'),
        bankBtn: ('button[value="Has had bankruptcy before"]'),
        foreBtn: ('button[value="Has had bankruptcy before"]'),
        yesBankForeBtn:('button[value="Has had both a foreclosure and a bankruptcy"]'),
        street: ('#addressOne'),
        street2: ('#addressTwo'),
        zipcode: ('#addressThree'),
        firstName: ('#first'),
        lastName: ('#last'),
        email: ('#email'),
        sendBtn: ('button[name="sendButton"]'),
        home: ('button[class="margin-btn"]'),

    }
}